# Generated by Django 3.2.8 on 2021-12-06 22:53

from django.db import migrations
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('BoardGameSocialAPI', '0001_initial'),
    ]

    operations = [
       
    ]
