# Generated by Django 3.2.8 on 2021-12-06 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BoardGameSocialAPI', '0002_auto_20211206_1453'),
    ]

    operations = [
         migrations.AddField(
            model_name='Post',
            name='dateTime',
            field=models.DateTimeField(db_column='dateTime', default=django.utils.timezone.now, null=True),
            
           
        ),
        migrations.AddField(
            model_name='Message',
            name='dateTime',
            field=models.DateTimeField(db_column='dateTime', default=django.utils.timezone.now,null=True),
            
        ),
    ]
